#! /bin/sh
xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output DP-1-3.2 --mode 3840x1080 --rotate normal --left-of eDP-1
bspc wm -O eDP-1 DP-1-3.2
bspc monitor eDP-1 -d 8 9 i
bspc monitor %DP-1-3.2 -d 1 2 3 4 5 6 7
bspc config border_width         5
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color	"#ce6600"
bspc config focused_border_color "#ce6600"
#539bf5


bspc rule -a Geany desktop='7' follow=on
bspc rule -a Brave-browser desktop='1' follow=on
bspc rule -a Portmaster desktop='i'
#bspc rule -a Xfce4-terminal desktop='^2' follow=on

#Autostart
sxhkd &
picom &
nitrogen --restore &
dunst &
polybar intern &
polybar extern &
nm-applet &
flatpak run com.core447.StreamController
flatpak run com.discordapp.Discord &
xsetroot -cursor_name left_ptr
/opt/safing/portmaster/portmaster-start app &
flatpak run org.remmina.Remmina & 
1password &
/usr/local/bin/QNAP/QsyncClient/Qsync.sh &
#(sleep 3 && bspc desktop --focus 1)
#(sleep 5 && xfce4-terminal)
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
numlockx on
